import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>あなたはロボットですか？ reCAPTCHAパロディ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action="#" method="post">
        <p>タイトル</p>
        <input type="text" placeholder="16字以内" />
        <div className='selectType' >
          <input type="radio" name="type" id="typeA" value="0" />
          <label htmlFor="typeA">タイプA</label>
          <input type="radio" name="type" id="typeB" value="8" />
          <label htmlFor="typeB">タイプB</label>
          <input type="radio" name="type" id="typeC" value="15" />
          <label htmlFor="typeC">タイプC</label>
        </div>
      </form>

      <Main></Main>


      <footer className={styles.footer}>
        フッター
      </footer>
    </div>
  )
}

export default Home
